name: teeklit_application
description: "Teeklit-은둔고립청년 커뮤니티 서비스"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.2.1
  #filename:pubspec.yaml
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.4
  image_picker: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true   # 이 줄이 있어야 함

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Paperlogy-9Black.ttf
          weight: 900

